### ISSUE TITLE
Unable to run apt-get update

### ISSUE THREAD

**Issue by QROkes** [rtCamp/easyengine#532] opened 2015-05-06 07:09 UTC
In a new / fresh AWS ec2 instance (ubuntu) I'm getting this error when trying to install EE.

EasyEngine (ee) installed successfully
EasyEngine (ee) help: http://docs.rtcamp.com/easyengine/
ubuntu@ip-172-31-32-127:~# sudo ee stack install
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Adding repository for HHVM, please wait...
Updating apt-cache, please wait...
Unable to run apt-get update

**Comment by MiteshShah** [comment] 2015-05-06 07:14
@QROkes 
Run following command and give us output

```
sudo apt-get update
```

**Comment by QROkes** [comment] 2015-05-06 07:30
I'm getting this error at the end:
.....
.......
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://mirror.aarnet.edu.au trusty/main amd64 Packages
Ign http://mirror.aarnet.edu.au trusty/main Translation-en_US
Ign http://mirror.aarnet.edu.au trusty/main Translation-en
Fetched 4,592 B in 3s (1,178 B/s)
Reading package lists... Done
W: GPG error: http://dl.hhvm.com trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A16E7281BE7A449
W: GPG error: http://mirror.aarnet.edu.au trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CBCB082A1BB943DB
ubuntu@ip-172-31-46-223:~$

**Comment by gau1991** [comment] 2015-05-06 08:16
Hello @QROkes ,
We are working on this and similar types on issue, #470, . We will fix this issue soon with new EasyEngine release. Until then fix for you is run following commands:
```
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
sudo apt-get update
```

**Comment by MiteshShah** [comment] 2015-05-06 08:17
Duplicate of #470 
All future discuss should be on #470

**Closed by MiteshShah** 2015-05-06 08:17 UTC
