### ISSUE TITLE
EasyEngine v3.1.4 | Can't install stack

### ISSUE THREAD

**Issue by wolerine** [rtCamp/easyengine#538] opened 2015-05-07 17:07 UTC
root@web:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
root@web:~# ee -v
EasyEngine v3.1.4
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.

root@web:/etc/apt/sources.list.d# ee stack install --all
System RAM is less than 1GB
Mail scanner packages are not going to install automatically
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Adding repository for HHVM, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Oops Something went wrong!!
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
root@web:/etc/apt/sources.list.d# tail /var/log/ee/ee.log
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mariadb-galera-server-10.0 : Depends: mariadb-client-10.0 (>= 10.0.17+maria-1~wheezy) but it is not installable
                              Depends: libmariadbclient18 (>= 10.0.17+maria-1~wheezy) but it is not installable
                              PreDepends: mariadb-common but it is not installable
                              Recommends: libhtml-template-perl but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
2015-05-07 20:03:02,650 (INFO) ee : Oops Something went wrong!!
2015-05-07 20:03:02,651 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!

I stuck when i am trying to install stack
I have tried with 32 bit, 64 bit also Ubuntu 14.04 with 32-64bit. Still the same problem.

**Comment by wolerine** [comment] 2015-05-07 18:41
I solved this problem but now another one happaned. 

root@web:/etc/apt# tail /var/log/ee/ee.log
2015-05-07 21:40:17,250 (DEBUG) ee : Running command: openssl req -new -batch  -subj /commonName=127.0.0.1/ -key /var/www/22222/cert/22222.key -out /var/www/22222/cert/22222.csr
2015-05-07 21:40:17,262 (DEBUG) ee : Moving file from /var/www/22222/cert/22222.key to /var/www/22222/cert/22222.key.org
2015-05-07 21:40:17,262 (DEBUG) ee : Running command: openssl rsa -in /var/www/22222/cert/22222.key.org -out /var/www/22222/cert/22222.key
2015-05-07 21:40:17,268 (DEBUG) ee : Running command: openssl x509 -req -days 3652 -in /var/www/22222/cert/22222.csr -signkey /var/www/22222/cert/22222.key -out /var/www/22222/cert/22222.crt
2015-05-07 21:40:17,299 (DEBUG) ee : EEGit: git commit at /etc/nginx
2015-05-07 21:40:17,337 (INFO) ee : Reload : nginx
2015-05-07 21:40:17,383 (DEBUG) ee : nginx: [emerg] "worker_rlimit_nofile" directive is duplicate in /etc/nginx/nginx.conf:4
nginx: configuration file /etc/nginx/nginx.conf test failed
2015-05-07 21:40:17,384 (INFO) ee : [Failed]
2015-05-07 21:40:19,135 (DEBUG) ee : Extracting file /tmp/pma.tar.gz to loaction /tmp/

i solve that problem also while editing nginx.conf but, after that i am getting 404 error on php files.
including port 22222

**Comment by gau1991** [comment] 2015-05-08 05:42
Hello @wolerine ,
```
2015-05-07 21:40:17,383 (DEBUG) ee : nginx: [emerg] "worker_rlimit_nofile" directive is duplicate in /etc/nginx/nginx.conf:4
```
To resolve this error do following
```
vim /etc/nginx/nginx.conf
```
and remove one line of `worker_rlimit_nofile` . after that,
```
nginx -t && service nginx reload
```
Also can you give me answer of following questions so that we will able to find exact cause of this issue:

1. Is EasyEngine fresh installed or updated from old release?
2. If possible can give us /var/log/ee.log file so that we can debug more.

**Comment by wolerine** [comment] 2015-05-08 07:04
Hello again.
Yes it is fresh install. I stuck again MariaDB install process and could not solve it yet.

I solved MariaDB issue before adding another repo into sources.list. But it did not help me this time.

You can check out : http://youtu.be/3Y1bX59427w

**Comment by gau1991** [comment] 2015-05-08 08:27
Hello @wolerine ,
Thanks for Video, Can you give me server access so that I can debug more.
You can add my key public key from http://docs.rtcamp.com/easyengine/keys.html

**Comment by gau1991** [comment] 2015-05-08 08:36
Hello @wolerine ,
I confirm this bug, This is introduced because of recent updates in MariaDB, so its is trying to install mariadb-galera-server-10.0. 
We analyzing this bug and soon we will fix this in EasyEngine..

**Comment by wolerine** [comment] 2015-05-08 08:59
Hello @gau1991
I have added you SSH key. My IP address is 188.166.1.45

**Comment by gau1991** [comment] 2015-05-08 11:01
Hello,
This is not bug from EasyEngine, this is from MariaDB repos itself. MariaDB packages are built for Wheezy but in these package are missing in index, so apt-get is not recognizing these packages.. 

Ref this mirror: http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.0/debian/dists/wheezy/main/binary-amd64/Packages.gz

**Comment by gau1991** [comment] 2015-05-08 11:39
Also reported to MariaDB bug tracker: https://mariadb.atlassian.net/browse/MDEV-8120

**Comment by MiteshShah** [comment] 2015-05-08 14:35
@gau1991 @wolerine Package is updated with new version

Refer: https://mariadb.atlassian.net/browse/MDEV-8118

Can you please try again and let me know

**Comment by gau1991** [comment] 2015-05-08 14:50
@MiteshShah 
MIrror update process is not instantaneous, it will take sometime hours to updates all mirrors..

**Comment by maxsinus** [comment] 2015-05-09 09:15
The status of https://mariadb.atlassian.net/browse/MDEV-8118 has been closed, yet the resolution won't fix.

**Comment by maxsinus** [comment] 2015-05-09 11:35
About nginx, I think related to this too, http://serverfault.com/questions/690265/nginx-1-6-3-to-1-8-upgrade/690313#690313

I can confirm that, after uprading to nginx 1.8.x the php-fpm doesn't work, it throwing a blank site.

**Comment by wolerine** [comment] 2015-05-09 13:00
I tested with Ubuntu 14.04 x64. There was not any problem. It seems it is only for Debian.

**Comment by MattyLB** [comment] 2015-05-09 20:10
I created two EC2 instances last night in an attempt to start fresh when an
update crashed my site and I initially received GPG errors, then did an apt
update & apt upgrade and installed ee without error, HOWEVER, php was
definitely having problems and I too was getting a blank white site with no
errors being thrown in the log and I verified all services were running,
restarted them and same issue. I'm now back on an Image I made of my
working ee 2.2.2 server and everything is great. I've had zero long term
success with any of the 3.x updates and I have a sneaking suspicion that
part of that issue is the way the nginx conf is changed and I have VERY
SPECIFIC ssl rules in place for one site.

**Comment by sonontse** [comment] 2015-05-12 22:12
I too have been having back to back issues with using easyengine with debian.  Decided to jump ship to Ubuntu and it seems to work fine.

**Comment by MiteshShah** [comment] 2015-05-13 11:36
@MattyLB @sonontse 

**Solution for white page on Debian:**

Add following line on `/etc/nginx/fastcgi_params` file
```
fastcgi_param SCRIPT_FILENAME $request_filename;
```
Now reload nginx

```
nginx -t && service nginx reload
```

**Closed** 2015-05-14 06:36 UTC
Labels: bug

**Comment by MattyLB** [comment] 2015-05-14 17:28
To clarify, I was using A Ubuntu stack, not Debian, so it was happening on
Ubuntu as well.  The real issue was that there are two upgrade paths, one
prior to 3.x and one for versions after - this is only mentioned on github
and not on the easy engine landing page on rtCamp.com. Once I followed the
github upgrade instructions, all was well. Just an FYI.
