### ISSUE TITLE
Feature request: Include Let's encrypt

### ISSUE THREAD

**Issue by NilsNojje** [rtCamp/easyengine#643] opened 2015-11-11 13:40 UTC
It would be nice if EE would have the ability to setup https/tls using Le's Encrypt when creating (or modifying) a host.

**Comment by karlhaworth** [comment] 2015-11-11 19:31
Duplicate.
https://github.com/rtCamp/easyengine/issues/376
https://github.com/rtCamp/easyengine/issues/559

**Comment by gau1991** [comment] 2015-11-12 07:07
Duplicate of #376 

letsencrypt.org - already on roadmap.

**Closed by gau1991** 2015-11-12 07:07 UTC
