### ISSUE TITLE
ee doesn't work anymore after update to Debian 8.1

### ISSUE THREAD

**Issue by ddelaey** [rtCamp/easyengine#587] opened 2015-07-19 13:26 UTC
ee doesn't work anymore after update to Debian 8.1 from Debian 7.8

ee version is 3.3.0

root@vm1855:~# lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.1 (jessie)
Release:	8.1
Codename:	jessie

root@vm1855:~# ee
Traceback (most recent call last):
  File "/usr/local/bin/ee", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ee==3.3.0

How to fix this?

Thanks, David

**Comment by ddelaey** [comment] 2015-07-19 13:32
ee version  is 3.3.0

**Comment by ddelaey** [comment] 2015-07-24 08:25
Is there anyone who can help?
Thanks, David

**Comment by rjdp** [comment] 2015-07-24 08:30
try reinstalling ee , if it doesn't help plz let me know along with the errors after reinstall .
"wget -qO ee rt.cx/ee && sudo bash ee"

**Comment by ddelaey** [comment] 2015-07-24 08:55
I tried reinstalling ee, but it terminated with the message that ee 3.3.0 was already installed.
Is there a command to ignore the current version and force reinstall?

Thanks, David

**Comment by rjdp** [comment] 2015-07-24 10:06
thats weird , since the latest version is 3.3.1 , 
it should've worked anyways ,fire this on your terminal ,
"ee update"

**Comment by ddelaey** [comment] 2015-07-24 10:18
That was the message from before 3.3.1 was available. Any ee command did not work.
"wget -qO ee rt.cx/ee && sudo bash ee" did the update to from 3.3.0 to 3.3.1 and now it's working fine again on that specific VPS.

The remaining question is:
If I'm already on the latest version of ee, is there a way to force reinstall ee (so, not being stopped by a ``` You already have EasyEngine 3.3.1, exit status =  1``` message)?
How do I need to do that?

It would be great knowing how to do that in case I (or someone else) have the same issue somewhere in future again.

Thanks for the support, David

**Comment by rjdp** [comment] 2015-07-24 11:07
@ddelaey , please continue your support questions at the community forum here: http://community.rtcamp.com/ 
This page is for discussions about the development of EE.

**Comment by harshadyeola** [comment] 2015-08-07 09:43
@ddelaey 
We have tested EasyEngine latest version over Debian 8.1. we are not able to reproduce issue.
I am closing this issue for now. Please create ticket on community forum (http://community.rtcamp.com/c/easyengine)

**Closed by harshadyeola** 2015-08-07 09:43 UTC
