### ISSUE TITLE
Failed to "ee stack install --web" on fresh ubuntu 14.04

### ISSUE THREAD

**Issue by sonontse** [rtCamp/easyengine#529] opened 2015-05-04 18:42 UTC
root@localhost:~# ee stack install --web
Postfix is already installed
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Adding repository for HHVM, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Unable to run apt-get install

```
2015-05-04 11:40:04,281 (DEBUG) ee : logging initialized for 'ee' using LoggingLogHandler
2015-05-04 11:40:04,486 (DEBUG) ee : ['/usr/local/bin/ee', 'sync']
2015-05-04 11:40:04,486 (DEBUG) ee : collecting arguments/commands for <ee.cli.controllers.base.EEBaseController object at 0x7fd51b663ba8>
2015-05-04 11:40:04,489 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.sync.EESyncController object at 0x7fd51b663d68>
2015-05-04 11:40:04,491 (INFO) ee : Initializing EasyEngine Database
2015-05-04 11:40:04,497 (INFO) ee : Synchronizing ee database, please wait...
2015-05-04 11:40:39,992 (DEBUG) ee : logging initialized for 'ee' using LoggingLogHandler
2015-05-04 11:40:40,191 (DEBUG) ee : ['/usr/local/bin/ee', 'stack', 'install', '--web']
2015-05-04 11:40:40,191 (DEBUG) ee : collecting arguments/commands for <ee.cli.controllers.base.EEBaseController object at 0x7f6d2be8acc0>
2015-05-04 11:40:40,194 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.stack.EEStackController object at 0x7f6d2be98160>
2015-05-04 11:40:40,195 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.stack_services.EEStackStatusController object at 0x7f6d2be98518>
2015-05-04 11:40:40,198 (INFO) ee : Initializing EasyEngine Database
2015-05-04 11:40:40,200 (DEBUG) ee : Setting apt_packages variable for Nginx
2015-05-04 11:40:41,066 (DEBUG) ee : Setting apt_packages variable for PHP
2015-05-04 11:40:41,983 (DEBUG) ee : Setting apt packages variable for HHVM
2015-05-04 11:40:42,946 (DEBUG) ee : Setting apt_packages variable for MySQL
2015-05-04 11:40:42,946 (DEBUG) ee : Running command: mysqladmin ping
2015-05-04 11:40:42,962 (DEBUG) ee : Command Output: ,
Command Error: /bin/sh: 1: mysqladmin: not found

2015-05-04 11:40:42,963 (DEBUG) ee : Setting apt_packages variable for Postfix
2015-05-04 11:40:43,929 (DEBUG) ee : Postfix is already installed
2015-05-04 11:40:43,929 (INFO) ee : Postfix is already installed
2015-05-04 11:40:43,930 (DEBUG) ee : Setting packages variable for WP-CLI
2015-05-04 11:40:43,930 (DEBUG) ee : Running command: which wp
2015-05-04 11:40:43,941 (DEBUG) ee : Command Output: ,
Command Error:
2015-05-04 11:40:43,942 (DEBUG) ee : Calling pre_pref
2015-05-04 11:40:43,942 (INFO) ee : Adding repository for MySQL, please wait...
2015-05-04 11:40:43,946 (DEBUG) ee : Adding key for deb http://mirror.aarnet.edu.au/pub/MariaDB/repo/10.0/ubuntu trusty main
2015-05-04 11:40:43,946 (DEBUG) ee : Running command: gpg --keyserver keyserver.ubuntu.com --recv-keys 0xcbcb082a1bb943db
2015-05-04 11:40:44,051 (DEBUG) ee : Running command: gpg -a --export --armor 0xcbcb082a1bb943db | apt-key add -
2015-05-04 11:40:44,095 (DEBUG) ee : Pre-seeding MySQL
2015-05-04 11:40:44,096 (DEBUG) ee : echo "mariadb-server-10.0 mysql-server/root_password password " | debconf-set-selections
2015-05-04 11:40:44,310 (DEBUG) ee : echo "mariadb-server-10.0 mysql-server/root_password_again password " | debconf-set-selections
2015-05-04 11:40:44,437 (DEBUG) ee : Writting configuration into MySQL file
2015-05-04 11:40:44,439 (INFO) ee : Adding repository for NGINX, please wait...
2015-05-04 11:40:44,439 (DEBUG) ee : Running command: add-apt-repository -y 'ppa:rtcamp/nginx'
2015-05-04 11:40:45,097 (DEBUG) ee : Adding ppa of Nginx
2015-05-04 11:40:45,097 (INFO) ee : Adding repository for PHP, please wait...
2015-05-04 11:40:45,097 (DEBUG) ee : Adding ppa for PHP
2015-05-04 11:40:45,098 (DEBUG) ee : Running command: add-apt-repository -y 'ppa:ondrej/php5-5.6'
2015-05-04 11:40:45,571 (INFO) ee : Adding repository for HHVM, please wait...
2015-05-04 11:40:45,571 (DEBUG) ee : Adding ppa repo for HHVM
2015-05-04 11:40:45,573 (DEBUG) ee : Adding HHVM GPG Key
2015-05-04 11:40:45,573 (DEBUG) ee : Running command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 0x5a16e7281be7a449
2015-05-04 11:40:45,870 (DEBUG) ee : Running command: gpg -a --export --armor 0x5a16e7281be7a449 | apt-key add -
2015-05-04 11:40:45,908 (INFO) ee : Updating apt-cache, please wait...
Ign http://archive.canonical.com trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease
Ign http://ppa.launchpad.net trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Hit http://archive.canonical.com trusty Release.gpg
Ign http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.canonical.com trusty Release
Get:1 http://ppa.launchpad.net trusty Release.gpg [316 B]
Hit http://archive.ubuntu.com trusty-updates Release.gpg
Get:2 http://ppa.launchpad.net trusty Release.gpg [836 B]
Hit http://archive.canonical.com trusty/partner amd64 Packages
Hit http://archive.ubuntu.com trusty Release
Get:3 http://ppa.launchpad.net trusty Release [15.1 kB]
Hit http://archive.ubuntu.com trusty-updates Release
Hit http://archive.canonical.com trusty/partner i386 Packages
Ign http://ppa.launchpad.net trusty Release
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Get:4 http://ppa.launchpad.net trusty Release [15.1 kB]
Ign http://archive.canonical.com trusty/partner Translation-en
Hit http://archive.ubuntu.com trusty/main i386 Packages
Get:5 http://ppa.launchpad.net trusty/main amd64 Packages [19.0 kB]
Hit http://archive.ubuntu.com trusty/restricted i386 Packages
Hit http://archive.ubuntu.com trusty/universe i386 Packages
Get:6 http://ppa.launchpad.net trusty/main i386 Packages [19.1 kB]
Get:7 http://ppa.launchpad.net trusty/main Translation-en [12.0 kB]
Hit http://archive.ubuntu.com trusty/main Translation-en
Get:8 http://ppa.launchpad.net trusty/main amd64 Packages [3452 B]
Hit http://archive.ubuntu.com trusty/restricted Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Get:9 http://ppa.launchpad.net trusty/main i386 Packages [3467 B]
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Get:10 http://ppa.launchpad.net trusty/main Translation-en [2632 B]
Get:11 http://dl.hhvm.com trusty InRelease [2104 B]
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Ign http://security.ubuntu.com trusty-security InRelease
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://archive.ubuntu.com trusty-updates/main Translation-en
Hit http://security.ubuntu.com trusty-security Release.gpg
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en
Get:12 http://dl.hhvm.com trusty/main amd64 Packages [1685 B]
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://security.ubuntu.com trusty-security Release
Get:13 http://dl.hhvm.com trusty/main i386 Packages [20 B]
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Get:14 http://mirror.aarnet.edu.au trusty InRelease [2488 B]
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
Ign http://dl.hhvm.com trusty/main Translation-en
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Get:15 http://mirror.aarnet.edu.au trusty/main amd64 Packages [5808 B]
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Get:16 http://mirror.aarnet.edu.au trusty/main i386 Packages [5800 B]
Ign http://mirror.aarnet.edu.au trusty/main Translation-en
Fetched 109 kB in 3s (32.1 kB/s)
Reading package lists...
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C
2015-05-04 11:40:51,555 (INFO) ee : Installing packages, please wait...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  autoconf automake autotools-dev build-essential debhelper dh-apparmor
  dh-php5 dpkg-dev fakeroot fonts-liberation g++ g++-4.8 gdb ghostscript
  gsfonts imagemagick-common intltool-debian libaio1 libalgorithm-diff-perl
  libalgorithm-diff-xs-perl libalgorithm-merge-perl libapparmor1
  libboost-context1.54.0 libboost-filesystem1.54.0
  libboost-program-options1.54.0 libboost-regex1.54.0 libboost-system1.54.0
  libboost-thread1.54.0 libc-client2007e libc6-dbg libcairo2 libcdt5
  libcgraph6 libcupsfilters1 libcupsimage2 libdatrie1 libdbd-mysql-perl
  libdbi-perl libdpkg-perl libelf1 libevent-2.0-5 libfakeroot libfftw3-double3
  libfile-fcntllock-perl libgd3 libgflags2 libgoogle-glog0 libgraphite2-3
  libgs9 libgs9-common libgvc6 libgvpr2 libharfbuzz0b libhtml-template-perl
  libice6 libicu52 libijs-0.35 libjasper1 libjbig0 libjbig2dec0 libjemalloc1
  libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libltdl-dev libluajit-5.1-2
  libluajit-5.1-common libmagickcore5 libmagickwand5 libmail-sendmail-perl
  libmariadbclient18 libmcrypt4 libmemcached10 libmysqlclient18 libonig2
  libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpathplan4
  libpcre3-dev libpcrecpp0 libpixman-1-0 libqdbm14 libreadline5 libsm6
  libssl-dev libssl-doc libstdc++-4.8-dev libsys-hostname-long-perl libtbb2
  libterm-readkey-perl libthai-data libthai0 libtiff5 libtimedate-perl libtool
  libunwind8 libvpx1 libx11-6 libx11-data libxau6 libxaw7 libxcb-render0
  libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxmu6 libxpm4 libxrender1
  libxslt1.1 libxt6 libyaml-0-2 mariadb-client-10.0 mariadb-client-core-10.0
  mariadb-common mariadb-server-10.0 mariadb-server-core-10.0 mlock
  mysql-common php5-json pkg-php-tools po-debconf poppler-data shtool
  x11-common zlib1g-dev
Suggested packages:
  autoconf2.13 autoconf-archive gnu-standards autoconf-doc dh-make
  apparmor-easyprof debian-keyring g++-multilib g++-4.8-multilib gcc-4.8-doc
  libstdc++6-4.8-dbg gdb-doc gdbserver ghostscript-x hpijs graphviz-doc
  uw-mailutils libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
  libsql-statement-perl libfftw3-bin libfftw3-dev libgd-tools fonts-droid
  libipc-sharedcache-perl libjasper-runtime liblcms2-utils libtool-doc
  libmagickcore5-extra libmcrypt-dev mcrypt ttf-baekmuk ttf-arphic-gbsn00lp
  ttf-arphic-bsmi00lp ttf-arphic-gkai00mp ttf-arphic-bkai00mp
  libstdc++-4.8-doc automaken gfortran fortran95-compiler gcj-jdk tinyca
  mariadb-test libcache-memcached-perl libmemcached fcgiwrap nginx-doc
  php5-user-cache libmail-box-perl poppler-utils fonts-japanese-mincho
  fonts-ipafont-mincho fonts-japanese-gothic fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-unfonts-core
Recommended packages:
  libc-dbg mysql-server
The following NEW packages will be installed:
  autoconf automake autotools-dev build-essential debhelper dh-apparmor
  dh-php5 dpkg-dev fakeroot fonts-liberation g++ g++-4.8 gdb ghostscript
  graphviz gsfonts hhvm imagemagick-common intltool-debian libaio1
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libapparmor1 libboost-context1.54.0 libboost-filesystem1.54.0
  libboost-program-options1.54.0 libboost-regex1.54.0 libboost-system1.54.0
  libboost-thread1.54.0 libc-client2007e libc6-dbg libcairo2 libcdt5
  libcgraph6 libcupsfilters1 libcupsimage2 libdatrie1 libdbd-mysql-perl
  libdbi-perl libdpkg-perl libelf1 libevent-2.0-5 libfakeroot libfftw3-double3
  libfile-fcntllock-perl libgd3 libgflags2 libgoogle-glog0 libgraphite2-3
  libgs9 libgs9-common libgvc6 libgvpr2 libharfbuzz0b libhtml-template-perl
  libice6 libicu52 libijs-0.35 libjasper1 libjbig0 libjbig2dec0 libjemalloc1
  libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libltdl-dev libluajit-5.1-2
  libluajit-5.1-common libmagickcore5 libmagickwand5 libmail-sendmail-perl
  libmariadbclient18 libmcrypt4 libmemcached10 libmysqlclient18 libonig2
  libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpathplan4
  libpcre3-dev libpcrecpp0 libpixman-1-0 libqdbm14 libreadline5 libsm6
  libssl-dev libssl-doc libstdc++-4.8-dev libsys-hostname-long-perl libtbb2
  libterm-readkey-perl libthai-data libthai0 libtiff5 libtimedate-perl libtool
  libunwind8 libvpx1 libx11-6 libx11-data libxau6 libxaw7 libxcb-render0
  libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxmu6 libxpm4 libxrender1
  libxslt1.1 libxt6 libyaml-0-2 mariadb-client-10.0 mariadb-client-core-10.0
  mariadb-common mariadb-server mariadb-server-10.0 mariadb-server-core-10.0
  memcached mlock mysql-common mysqltuner nginx-common nginx-custom
  percona-toolkit php-pear php5-cli php5-common php5-curl php5-dev php5-fpm
  php5-gd php5-imagick php5-imap php5-json php5-mcrypt php5-memcache
  php5-mysql php5-readline php5-xdebug pkg-php-tools po-debconf poppler-data
  shtool x11-common zlib1g-dev
0 upgraded, 150 newly installed, 0 to remove and 12 not upgraded.
Need to get 87.7 MB of archives.
After this operation, 369 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libgd3 php5-common php5-json php5-cli php-pear php5-curl php5-dev php5-fpm
  php5-gd php5-imagick php5-imap php5-mcrypt php5-memcache php5-mysql
  php5-readline php5-xdebug dh-php5 pkg-php-tools
E: There are problems and -y was used without --force-yes
2015-05-04 11:40:52,050 (ERROR) ee : Unable to run apt-get install
```

**Comment by MiteshShah** [comment] 2015-05-05 05:14
```
WARNING: The following packages cannot be authenticated!
  libgd3 php5-common php5-json php5-cli php-pear php5-curl php5-dev php5-fpm
  php5-gd php5-imagick php5-imap php5-mcrypt php5-memcache php5-mysql
  php5-readline php5-xdebug dh-php5 pkg-php-tools
E: There are problems and -y was used without --force-yes
2015-05-04 11:40:52,050 (ERROR) ee : Unable to run apt-get install
```

Duplicate of #470

**Closed by MiteshShah** 2015-05-05 05:14 UTC
