### ISSUE TITLE
Multiple WordPress Installations

### ISSUE THREAD

**Issue by eliasjnior** [rtCamp/easyengine#553] opened 2015-05-23 04:28 UTC
I'm trying to install multiple WP, just for test at the moment, but I can't make it right, because the permalinks doesn't works, and I think that cache and other things are probably not working too.

I logged in phpmyadmin with root user, created a new database, make the correct user with privilegies, and this step is working fine.

The problem is that when I try to access http://eliasjrweb.com/wordpress/post-example/ it's showing 404. In the page http://eliasjrweb.com/wordpress/ it's working, just the things that needs permalinks.

I already tried some nginx settings, but didin't work for me, or maybe I did it wrong. 

So what we have to do to make multiple installations in a domain?

**Comment by eliasjnior** [comment] 2015-05-23 04:33
Oh, I just found the solution :+1: 

For who wants, just edit  ```ee site edit example.com``` and add in the end of the file, before end "server":

```
location /blog {
    index index.php;
    rewrite ^/blog/(.*)+$ /blog/index.php?$1;
}
```

But will that make everything working like in the root of the domain? Cache, security, and everything?

**Comment by rippler** [comment] 2015-05-23 04:52
This isn't a bug because that's not a WP installation (by EE), it's your own installation of WP.

**Comment by eliasjnior** [comment] 2015-05-23 13:00
@rippler, yes, it was my own installation, but, don't you think that EE should come with some arg to select installation on subdir?

**Comment by rippler** [comment] 2015-05-23 13:30
I mean, you installed WP on your own *after* you created a Web (not WP) site. How can EE know what you're going to do next?  So in view of current capabilities, I don't think this is an EE problem.

It seems you'd like to use EE to install WP to particular directory, or maybe install a PHP/mySQL site (possible), manually install WP (possible) and then run a EE modify command to add a location rule to the PHP/mySQL site you created (not available). You could create an enhancement request for that, but I don't think this is a bug.

**Comment by w33zy** [comment] 2015-05-23 14:06
As per what @rippler wrote, creating multiple installations of WP using wp1.domain.com; wp2.domain.com; etc, is a more "semantic" way of doing things. Also, it has the added benefit of being covered by EE

**Comment by MattyLB** [comment] 2015-05-23 14:11
@rippler - I agree 100%.

We've been "given" an amazing tool that allows us to decide which path we
want to take for a particular site.

We should choose our path wisely and not expect EE to lay fresh cement if
the path we have chosen has a gravel foundation.

#kiss - (keep it simple & stable)

**Comment by gau1991** [comment] 2015-05-23 14:24
@eliasjnior ,
This will help you: https://github.com/rtCamp/easyengine/issues/31#issue-17163315
I am closing this issue, as this is duplicate of #31

**Closed by gau1991** 2015-05-23 14:24 UTC

**Comment by puccaso** [comment] 2016-03-13 16:59
Can we get an update on this item?

Single Install Site on a sub Directory....

how does one accomplish it?

i'm using the most recent EE ..
