### ISSUE TITLE
PHP Failed to Restart after Upgrade

### ISSUE THREAD

**Issue by irazasyed** [rtCamp/easyengine#551] opened 2015-05-21 21:11 UTC
Something's wrong with `3.1.7`. I just updated and fired the stack upgrade command.

At the end of it, It started to restart the stack and then it seems like it tried to restart `php` and not `php5-fpm` like with the standard `ee stack restart` (Which works fine).

So it ended up showing status as Failed.

I'm on Ubuntu btw.

P.S Updated on 2 of my droplets and both show the same thing.

**Comment by gau1991** [comment] 2015-05-22 05:36
Duplicate of #550 .
Hello We fixed this bug in master Branch, soon it will be released with new version of EasyEngine.

**Closed by gau1991** 2015-05-22 05:36 UTC
