### ISSUE TITLE
Unable to run apt-get install Error on fresh install

### ISSUE THREAD

**Issue by desaiuditd** [rtCamp/easyengine#507] opened 2015-04-24 08:15 UTC
I followed these steps to install easyengine on a fresh Ubuntu 14.04 Linode server.

- `wget -qO ee rt.cx/ee && sudo bash ee`
- `source /etc/bash_completion.d/ee_auto.rc`
- `ee site create example.com --wp`

And then I got the following terminal error.

![screen shot 2015-04-24 at 13 40 42](https://cloud.githubusercontent.com/assets/2236554/7315019/bda7b050-ea87-11e4-8681-d961ab2c2139.png)

Any resolution to this ?

**Comment by MiteshShah** [comment] 2015-04-24 08:18
@desaiuditd Can you give us /var/log/easyengine/*.log file output

Its seems like GPG key issue need to check your logs.

**Comment by desaiuditd** [comment] 2015-04-24 08:25
Here is the output for `ee.log` file.

```
2015-04-24 04:10:09,625 (DEBUG) ee : logging initialized for 'ee' using LoggingLogHandler
2015-04-24 04:10:09,941 (DEBUG) ee : ['/usr/local/bin/ee', 'site', 'create', 'example.com', '--wp']
2015-04-24 04:10:09,942 (DEBUG) ee : collecting arguments/commands for <ee.cli.controllers.base.EEBaseController object at 0x7fbb81d84748>
2015-04-24 04:10:09,946 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.site.EESiteController object at 0x7fbb81d84e48>
2015-04-24 04:10:09,948 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.site.EESiteCreateController object at 0x7fbb81d8f160>
2015-04-24 04:10:09,951 (INFO) ee : Initializing EasyEngine Database
2015-04-24 04:10:09,961 (DEBUG) ee : Setting apt_packages variable for Nginx
2015-04-24 04:10:11,537 (DEBUG) ee : Setting apt_packages variable for PHP
2015-04-24 04:10:13,074 (DEBUG) ee : Setting apt_packages variable for MySQL
2015-04-24 04:10:13,075 (DEBUG) ee : Running command: mysqladmin ping
2015-04-24 04:10:13,106 (DEBUG) ee : Command Output: , 
Command Error: /bin/sh: 1: mysqladmin: not found

2015-04-24 04:10:13,107 (DEBUG) ee : Setting apt_packages variable for Postfix
2015-04-24 04:10:14,609 (DEBUG) ee : Setting packages variable for WP-CLI
2015-04-24 04:10:14,610 (DEBUG) ee : Running command: which wp
2015-04-24 04:10:14,649 (DEBUG) ee : Command Output: , 
Command Error: 
2015-04-24 04:10:14,649 (DEBUG) ee : Calling pre_pref
2015-04-24 04:10:14,649 (DEBUG) ee : Pre-seeding Postfix
2015-04-24 04:10:14,649 (DEBUG) ee : Running command: echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
2015-04-24 04:10:14,824 (DEBUG) ee : Running command: echo "postfix postfix/mailname string $(hostname -f)" | debconf-set-selections
2015-04-24 04:10:14,995 (INFO) ee : Adding repository for MySQL, please wait ...
2015-04-24 04:10:14,996 (DEBUG) ee : Adding key for deb http://mirror.aarnet.edu.au/pub/MariaDB/repo/10.0/ubuntu trusty main
2015-04-24 04:10:14,996 (DEBUG) ee : Running command: gpg --keyserver keyserver.ubuntu.com --recv-keys 0xcbcb082a1bb943db
2015-04-24 04:10:15,340 (DEBUG) ee : Running command: gpg -a --export --armor 0xcbcb082a1bb943db | apt-key add - 
2015-04-24 04:10:15,478 (DEBUG) ee : Pre-seeding MySQL
2015-04-24 04:10:15,479 (DEBUG) ee : echo "mariadb-server-10.0 mysql-server/root_password password " | debconf-set-selections
2015-04-24 04:10:15,655 (DEBUG) ee : echo "mariadb-server-10.0 mysql-server/root_password_again password " | debconf-set-selections
2015-04-24 04:10:15,827 (DEBUG) ee : Writting configuration into MySQL file
2015-04-24 04:10:15,828 (INFO) ee : Adding repository for NGINX, please wait ...
2015-04-24 04:10:15,828 (DEBUG) ee : Running command: add-apt-repository -y 'ppa:rtcamp/nginx'
2015-04-24 04:10:17,341 (DEBUG) ee : Adding ppa of Nginx
2015-04-24 04:10:17,342 (INFO) ee : Adding repository for PHP, please wait ...
2015-04-24 04:10:17,342 (DEBUG) ee : Adding ppa for PHP
2015-04-24 04:10:17,342 (DEBUG) ee : Running command: add-apt-repository -y 'ppa:ondrej/php5'
2015-04-24 04:10:18,844 (INFO) ee : Updating apt-cache, please wait ...
Ign http://mirrors.linode.com trusty InRelease
Ign http://mirrors.linode.com trusty-updates InRelease
Ign http://mirrors.linode.com trusty-backports InRelease
Hit http://mirrors.linode.com trusty Release.gpg
Hit http://mirrors.linode.com trusty-updates Release.gpg
Hit http://mirrors.linode.com trusty-backports Release.gpg
Hit http://mirrors.linode.com trusty Release
Hit http://mirrors.linode.com trusty-updates Release
Hit http://mirrors.linode.com trusty-backports Release
Hit http://mirrors.linode.com trusty/main Sources
Hit http://mirrors.linode.com trusty/restricted Sources
Hit http://mirrors.linode.com trusty/universe Sources
Hit http://mirrors.linode.com trusty/multiverse Sources
Hit http://mirrors.linode.com trusty/main amd64 Packages
Hit http://mirrors.linode.com trusty/restricted amd64 Packages
Hit http://mirrors.linode.com trusty/universe amd64 Packages
Hit http://mirrors.linode.com trusty/multiverse amd64 Packages
Hit http://mirrors.linode.com trusty/main i386 Packages
Hit http://mirrors.linode.com trusty/restricted i386 Packages
Hit http://mirrors.linode.com trusty/universe i386 Packages
Hit http://mirrors.linode.com trusty/multiverse i386 Packages
Hit http://mirrors.linode.com trusty/main Translation-en
Hit http://mirrors.linode.com trusty/multiverse Translation-en
Hit http://mirrors.linode.com trusty/restricted Translation-en
Hit http://mirrors.linode.com trusty/universe Translation-en
Hit http://mirrors.linode.com trusty-updates/main Sources
Hit http://mirrors.linode.com trusty-updates/restricted Sources
Hit http://mirrors.linode.com trusty-updates/universe Sources
Hit http://mirrors.linode.com trusty-updates/multiverse Sources
Hit http://mirrors.linode.com trusty-updates/main amd64 Packages
Hit http://mirrors.linode.com trusty-updates/restricted amd64 Packages
Hit http://mirrors.linode.com trusty-updates/universe amd64 Packages
Hit http://mirrors.linode.com trusty-updates/multiverse amd64 Packages
Hit http://mirrors.linode.com trusty-updates/main i386 Packages
Hit http://mirrors.linode.com trusty-updates/restricted i386 Packages
Hit http://mirrors.linode.com trusty-updates/universe i386 Packages
Hit http://mirrors.linode.com trusty-updates/multiverse i386 Packages
Hit http://mirrors.linode.com trusty-updates/main Translation-en
Hit http://mirrors.linode.com trusty-updates/multiverse Translation-en
Hit http://mirrors.linode.com trusty-updates/restricted Translation-en
Hit http://mirrors.linode.com trusty-updates/universe Translation-en
Hit http://mirrors.linode.com trusty-backports/main Sources
Hit http://mirrors.linode.com trusty-backports/restricted Sources
Hit http://mirrors.linode.com trusty-backports/universe Sources
Hit http://mirrors.linode.com trusty-backports/multiverse Sources
Ign http://ppa.launchpad.net trusty InRelease
Hit http://mirrors.linode.com trusty-backports/main amd64 Packages
Hit http://mirrors.linode.com trusty-backports/restricted amd64 Packages
Hit http://mirrors.linode.com trusty-backports/universe amd64 Packages
Hit http://mirrors.linode.com trusty-backports/multiverse amd64 Packages
Hit http://mirrors.linode.com trusty-backports/main i386 Packages
Hit http://mirrors.linode.com trusty-backports/restricted i386 Packages
Hit http://mirrors.linode.com trusty-backports/universe i386 Packages
Hit http://mirrors.linode.com trusty-backports/multiverse i386 Packages
Hit http://mirrors.linode.com trusty-backports/main Translation-en
Hit http://mirrors.linode.com trusty-backports/multiverse Translation-en
Ign http://security.ubuntu.com trusty-security InRelease
Hit http://mirrors.linode.com trusty-backports/restricted Translation-en
Hit http://mirrors.linode.com trusty-backports/universe Translation-en
Ign http://ppa.launchpad.net trusty InRelease
Get:1 http://security.ubuntu.com trusty-security Release.gpg [933 B]
Get:2 http://ppa.launchpad.net trusty Release.gpg [316 B]
Get:3 http://security.ubuntu.com trusty-security Release [63.5 kB]
Hit http://ppa.launchpad.net trusty Release.gpg
Hit http://ppa.launchpad.net trusty Release
Ign http://ppa.launchpad.net trusty Release
Hit http://mirror.aarnet.edu.au trusty InRelease
Hit http://ppa.launchpad.net trusty Release
Ign http://ppa.launchpad.net trusty/main amd64 Packages/DiffIndex
Get:4 http://security.ubuntu.com trusty-security/main Sources [78.7 kB]
Ign http://ppa.launchpad.net trusty/main i386 Packages/DiffIndex
Hit http://mirror.aarnet.edu.au trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Get:5 http://security.ubuntu.com trusty-security/restricted Sources [2061 B]
Hit http://ppa.launchpad.net trusty/main i386 Packages
Hit http://mirror.aarnet.edu.au trusty/main i386 Packages
Get:6 http://security.ubuntu.com trusty-security/universe Sources [20.9 kB]
Hit http://ppa.launchpad.net trusty/main Translation-en
Get:7 http://security.ubuntu.com trusty-security/multiverse Sources [1922 B]
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [259 kB]
Hit http://ppa.launchpad.net trusty/main i386 Packages
Get:9 http://security.ubuntu.com trusty-security/restricted amd64 Packages [8875 B]
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [99.7 kB]
Get:11 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [3451 B]
Get:12 http://security.ubuntu.com trusty-security/main i386 Packages [248 kB]
Ign http://mirror.aarnet.edu.au trusty/main Translation-en
Get:13 http://security.ubuntu.com trusty-security/restricted i386 Packages [8846 B]
Get:14 http://security.ubuntu.com trusty-security/universe i386 Packages [99.7 kB]
Get:15 http://security.ubuntu.com trusty-security/multiverse i386 Packages [3643 B]
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Fetched 899 kB in 3s (295 kB/s)
Reading package lists...
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C
2015-04-24 04:10:24,568 (INFO) ee : Installing packages, please wait ...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core fonts-liberation gdb
  ghostscript gsfonts imagemagick-common libaio1 libavahi-client3
  libavahi-common-data libavahi-common3 libc-client2007e libc6-dbg libcairo2
  libcdt5 libcgraph6 libcups2 libcupsfilters1 libcupsimage2 libdatrie1
  libdbd-mysql-perl libdbi-perl libfftw3-double3 libfontconfig1 libfreetype6
  libgd3 libgraphite2-3 libgs9 libgs9-common libgvc6 libgvpr2 libharfbuzz0b
  libhtml-template-perl libice6 libijs-0.35 libjasper1 libjbig0 libjbig2dec0
  libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libltdl7 libluajit-5.1-2
  libluajit-5.1-common libmagickcore5 libmagickwand5 libmariadbclient18
  libmcrypt4 libmysqlclient18 libonig2 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpaper-utils libpaper1 libpathplan4 libpixman-1-0
  libqdbm14 libsm6 libterm-readkey-perl libthai-data libthai0 libtiff5 libvpx1
  libx11-6 libx11-data libxaw7 libxcb-render0 libxcb-shm0 libxext6 libxmu6
  libxpm4 libxrender1 libxslt1.1 libxt6 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server-10.0
  mariadb-server-core-10.0 mlock mysql-common php5-json poppler-data ssl-cert
  ttf-dejavu-core x11-common
Suggested packages:
  gdb-doc gdbserver ghostscript-x hpijs graphviz-doc uw-mailutils cups-common
  libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
  libsql-statement-perl libfftw3-bin libfftw3-dev libgd-tools fonts-droid
  libipc-sharedcache-perl libjasper-runtime liblcms2-utils
  libmagickcore5-extra libmcrypt-dev mcrypt ttf-baekmuk ttf-arphic-gbsn00lp
  ttf-arphic-bsmi00lp ttf-arphic-gkai00mp ttf-arphic-bkai00mp tinyca mailx
  mariadb-test libcache-memcached-perl libmemcached fcgiwrap nginx-doc
  php-pear php5-user-cache poppler-utils fonts-japanese-mincho
  fonts-ipafont-mincho fonts-japanese-gothic fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-unfonts-core procmail
  postfix-mysql postfix-pgsql postfix-ldap postfix-pcre sasl2-bin
  dovecot-common postfix-cdb mail-reader postfix-doc openssl-blacklist
Recommended packages:
  libc-dbg mysql-server
The following NEW packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core fonts-liberation gdb
  ghostscript graphviz gsfonts imagemagick-common libaio1 libavahi-client3
  libavahi-common-data libavahi-common3 libc-client2007e libc6-dbg libcairo2
  libcdt5 libcgraph6 libcups2 libcupsfilters1 libcupsimage2 libdatrie1
  libdbd-mysql-perl libdbi-perl libfftw3-double3 libfontconfig1 libfreetype6
  libgd3 libgraphite2-3 libgs9 libgs9-common libgvc6 libgvpr2 libharfbuzz0b
  libhtml-template-perl libice6 libijs-0.35 libjasper1 libjbig0 libjbig2dec0
  libjpeg-turbo8 libjpeg8 liblcms2-2 liblqr-1-0 libltdl7 libluajit-5.1-2
  libluajit-5.1-common libmagickcore5 libmagickwand5 libmariadbclient18
  libmcrypt4 libmysqlclient18 libonig2 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpaper-utils libpaper1 libpathplan4 libpixman-1-0
  libqdbm14 libsm6 libterm-readkey-perl libthai-data libthai0 libtiff5 libvpx1
  libx11-6 libx11-data libxaw7 libxcb-render0 libxcb-shm0 libxext6 libxmu6
  libxpm4 libxrender1 libxslt1.1 libxt6 mariadb-client-10.0
  mariadb-client-core-10.0 mariadb-common mariadb-server mariadb-server-10.0
  mariadb-server-core-10.0 memcached mlock mysql-common mysqltuner
  nginx-common nginx-custom percona-toolkit php5-cli php5-common php5-curl
  php5-fpm php5-gd php5-imagick php5-imap php5-json php5-mcrypt php5-memcache
  php5-mysql php5-readline php5-xdebug poppler-data postfix ssl-cert
  ttf-dejavu-core x11-common
0 upgraded, 109 newly installed, 0 to remove and 4 not upgraded.
Need to get 51.5 MB of archives.
After this operation, 288 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  php5-common php5-curl php5-json php5-cli php5-fpm php5-gd php5-imap
  php5-mcrypt php5-mysql php5-readline php5-imagick php5-memcache php5-xdebug
E: There are problems and -y was used without --force-yes
2015-04-24 04:10:25,234 (ERROR) ee : Unable to run apt-get install
```

**Comment by desaiuditd** [comment] 2015-04-24 08:27
@MiteshShah Do I need to give `install.log` ? I checked that log. Doesn't seem to be any conflict there.

**Comment by MiteshShah** [comment] 2015-04-24 08:32
@desaiuditd 
Error: 
```
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C 2015-04-24 04:10:24,568 (INFO) ee : Installing packages, please wait ...
```

How to fix: https://github.com/rtCamp/easyengine/issues/245#issuecomment-43303332

**Comment by desaiuditd** [comment] 2015-04-24 08:41
@MiteshShah In the comment on https://github.com/rtCamp/easyengine/issues/245#issuecomment-48272057 @gau1991 has mentioned to set the flag in `ee.conf` file. I see there are multiple sections in that file like,

```
[ee]
....
....
[log.logging]
....
....
[stack]

[mysql]

etc.
```

My question is, under which section do I have to set the flag for `gpg-keys-fix` ?

**Comment by MiteshShah** [comment] 2015-04-24 08:45
@desaiuditd That flag is available for EE 2.x and i guess its removed in EE 3.x
@gau1991 can you confirm same please.

**Comment by rahul286** [comment] 2015-04-24 08:48
On sidenote, rather than having a flag for `gpg-keys-fix`, if there is a gpg-key issue, it should be fixed automatically IMHO.

I mean who doesn't want to fix keys. It should not be optional.

**Comment by gau1991** [comment] 2015-04-24 08:48
@desaiuditd @MiteshShah 
That flag is removed in EasyEngine 3.x

**Comment by desaiuditd** [comment] 2015-04-24 09:00
Okay, Thanks guys. @MiteshShah @gau1991 

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
```

Above command fixed it for me. However I will keep this open if you want to fix this in EE 3.x as @rahul286 suggested.

**Comment by gau1991** [comment] 2015-04-24 09:04
@MiteshShah @rahul286 

I was digging into this issue. The main issue I found that, the issue is with Ondrej repo only. 
```
gpg: /tmp/tmptxhd3gxt/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 687, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 370, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 261, in add_ppa_signing_key
    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 210, in _verify_fingerprint
    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 202, in _get_fingerprints
    output = subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 605, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "/usr/lib/python3.4/subprocess.py", line 936, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python3.4/subprocess.py", line 487, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)
```

there are some special characters in the name of Ondrej Sury: `gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported`. 

This characters are  supported by UTF-8 encoding. If someone system don't have UTF-8 encoding,  Then apt-add-repository command throws error and EasyEngine fails to install packages.  This terminal encoding is set client terminal.
Possible solutions to fix this problem are:
1. Set default encoding to UTF-8 in `.bash_rc`
2.  Instead of using apt-add-repository use of following commands:
```
touch /etc/apt/sources.list.d/ondrej-php5.list
echo "deb http://ppa.launchpad.net/ondrej/php5/ubuntu trusty main" >> /etc/apt/sources.list.d/ondrej-php5.list
echo "deb-src http://ppa.launchpad.net/ondrej/php5/ubuntu trusty main" >> /etc/apt/sources.list.d/ondrej-php5.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
```

**Comment by MiteshShah** [comment] 2015-04-24 09:16
@gau1991 :+1: 

> Instead of using apt-add-repository use of following commands:
```
touch /etc/apt/sources.list.d/ondrej-php5.list
echo "deb http://ppa.launchpad.net/ondrej/php5/ubuntu trusty main" >> /etc/apt/sources.list.d/ondrej-php5.list
echo "deb-src http://ppa.launchpad.net/ondrej/php5/ubuntu trusty main" >> /etc/apt/sources.list.d/ondrej-php5.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C
```

Dont need to touch file echo will do that :)

**Comment by MiteshShah** [comment] 2015-05-05 05:11
@desaiuditd @gau1991 Closing this issue and all future discussion on this topic should be on #470

**Closed by MiteshShah** 2015-05-05 05:11 UTC
