### ISSUE TITLE
ee_platform_distro is not "debian"

### ISSUE THREAD

**Issue by cicoub13** [rtCamp/easyengine#525] opened 2015-05-02 00:14 UTC
I try to install full stack on Debian 7 and i've got this error :`type object 'EEVariables' has no attribute 'ee_nginx'`.
I searched and i found that command `platform.linux_distribution()` is not equal to "**debian**" but "**Debian**". So variables are not set correctly in variables.py

`ee --version
EasyEngine v3.1.2
Copyright (c) 2015 rtCamp Solutions Pvt. Ltd.`

**Comment by gau1991** [comment] 2015-05-07 06:48
@cicoub13 ,
We are not able to reproduce this issue on Debian 7.8. 
Can you please update all your packages, and check again?
I am closing this issue now, feel free to reopen if face this again.

**Closed by gau1991** 2015-05-07 06:48 UTC

**Comment by cicoub13** [comment] 2015-05-07 13:01
My server is a Kimsufi 2G hosted by OVH France.

EasyeEngine use python linux_distribution (base on etc/lsb-release).
```python
ee_platform_distro = platform.linux_distribution()[0]
```

```bash
cat /etc/lsb-release
DISTRIB_ID=Debian
DISTRIB_RELEASE=7
DISTRIB_CODENAME=
DISTRIB_DESCRIPTION=
```

I can suggest a pull request with ".lower()" to correct if necessary.
